// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiIiQ9M11Cmp_TNaie9_V1pP-wmW5Gw_g',
    appId: '1:308392785540:web:b82a9a58b3f048893bf4d1',
    messagingSenderId: '308392785540',
    projectId: 'signin-ccab9',
    authDomain: 'signin-ccab9.firebaseapp.com',
    storageBucket: 'signin-ccab9.firebasestorage.app',
    measurementId: 'G-9K5HFJNR1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9FpzqnxeMYxkMPtnI6d3tsIR5oAqg83g',
    appId: '1:308392785540:android:0d8cda579f5a7c073bf4d1',
    messagingSenderId: '308392785540',
    projectId: 'signin-ccab9',
    storageBucket: 'signin-ccab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_e4b6NPhoXt8D3331GvIt8RqnjHlplEQ',
    appId: '1:308392785540:ios:b3ef410dc905e9933bf4d1',
    messagingSenderId: '308392785540',
    projectId: 'signin-ccab9',
    storageBucket: 'signin-ccab9.firebasestorage.app',
    androidClientId: '308392785540-d74spj7j7ntnlb0chu8s65ffravbkdep.apps.googleusercontent.com',
    iosClientId: '308392785540-htq3am54fcdr0k2qbliqokq4619nt1ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemax',
  );
}
